### ISSUE TITLE
utils/parse_options.sh short

### ISSUE THREAD

**Issue by feipeng-wang** [fchest/Speech-Transformer-multi-GPUs#1]
where I was running bash run.sh under egs/aishell. It spited: run.sh line 71: utils/parse_options.sh: No such file or directory . it seems you have folder utils short compared with https://github.com/kaituoxu/Speech-Transformer/tree/master/egs/aishell. So any ideas?

**Comment by feipeng-wang** [comment]
Added thanks @fchest !

**Comment by fchest** [comment]
> where I was running bash run.sh under egs/aishell. It spited: run.sh line 71: utils/parse_options.sh: No such file or directory . it seems you have folder utils short compared with https://github.com/kaituoxu/Speech-Transformer/tree/master/egs/aishell. So any ideas?

you can use the " ln -s " to link the steps and utils from your kaldi path

**Comment by feipeng-wang** [comment]
Thanks. However, afterward, I came across the problem. 
"Speech-Transformer-multi-GPUs/egs/aishell$ sudo bash run.sh
dictionary: data/lang_1char/train_chars.txt
stage 4: Decoding
2020-04-09 08:49:12,161 (json2trn:28) INFO: reading exp/train_m4_n3_in80_elayer6_head8_k64_v64_model512_inner2048_drop0.1_pe5000_emb512_dlayer6_share1_ls0.1_epoch150_shuffle1_bs32_bf15000_mli800_mlo150_k0.2_warm4000/decode_test_beam5_nbest1_ml100/data.json
Traceback (most recent call last):
  File "/opt/py_virtualenv/torch0.4.1/Speech-Transformer-multi-GPUs/egs/aishell/../../src/utils/json2trn.py", line 29, in <module>
    with open(args.json, 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'exp/train_m4_n3_in80_elayer6_head8_k64_v64_model512_inner2048_drop0.1_pe5000_emb512_dlayer6_share1_ls0.1_epoch150_shuffle1_bs32_bf15000_mli800_mlo150_k0.2_warm4000/decode_test_beam5_nbest1_ml100/data.json'
cp: cannot stat 'exp/train_m4_n3_in80_elayer6_head8_k64_v64_model512_inner2048_drop0.1_pe5000_emb512_dlayer6_share1_ls0.1_epoch150_shuffle1_bs32_bf15000_mli800_mlo150_k0.2_warm4000/decode_test_beam5_nbest1_ml100/ref.trn': No such file or directory
cp: cannot stat 'exp/train_m4_n3_in80_elayer6_head8_k64_v64_model512_inner2048_drop0.1_pe5000_emb512_dlayer6_share1_ls0.1_epoch150_shuffle1_bs32_bf15000_mli800_mlo150_k0.2_warm4000/decode_test_beam5_nbest1_ml100/hyp.trn': No such file or directory
local/score.sh: line 22: exp/train_m4_n3_in80_elayer6_head8_k64_v64_model512_inner2048_drop0.1_pe5000_emb512_dlayer6_share1_ls0.1_epoch150_shuffle1_bs32_bf15000_mli800_mlo150_k0.2_warm4000/decode_test_beam5_nbest1_ml100/ref.trn: No such file or directory
local/score.sh: line 23: exp/train_m4_n3_in80_elayer6_head8_k64_v64_model512_inner2048_drop0.1_pe5000_emb512_dlayer6_share1_ls0.1_epoch150_shuffle1_bs32_bf15000_mli800_mlo150_k0.2_warm4000/decode_test_beam5_nbest1_ml100/hyp.trn: No such file or directory
local/score.sh: line 26: exp/train_m4_n3_in80_elayer6_head8_k64_v64_model512_inner2048_drop0.1_pe5000_emb512_dlayer6_share1_ls0.1_epoch150_shuffle1_bs32_bf15000_mli800_mlo150_k0.2_warm4000/decode_test_beam5_nbest1_ml100/result.txt: No such file or directory
write a CER (or TER) result in exp/train_m4_n3_in80_elayer6_head8_k64_v64_model512_inner2048_drop0.1_pe5000_emb512_dlayer6_share1_ls0.1_epoch150_shuffle1_bs32_bf15000_mli800_mlo150_k0.2_warm4000/decode_test_beam5_nbest1_ml100/result.txt
grep: exp/train_m4_n3_in80_elayer6_head8_k64_v64_model512_inner2048_drop0.1_pe5000_emb512_dlayer6_share1_ls0.1_epoch150_shuffle1_bs32_bf15000_mli800_mlo150_k0.2_warm4000/decode_test_beam5_nbest1_ml100/result.txt: No such file or directory
" 
I checked that file. the data.json is not generated.

**Comment by feipeng-wang** [comment]
There are so many issues  that need  to be clarified. As far as I can see, most of them concern about  the paths and ENV variables.  I will keep you updated when I walked through.  It would be nice if you could specify the impementation in more details.
